services:
  db:
    image: mysql:8.0
    container_name: coderun-modern-lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - coderun-modern-lms-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: coderun-modern-lms-backend
    restart: always
    user: root
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
      - ./public:/backend/public
      - /backend/node_modules
      # - /var/run/docker.sock:/var/run/docker.sock
      - ./temp:/temp
    command: nodemon -L index.js

volumes:
  coderun-modern-lms-mysql:
