FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    openjdk-17-jdk \
    coreutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN useradd -m sandbox

RUN chown sandbox:sandbox /app

USER sandbox

CMD ["bash"]